import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

const faqs = [
  {
    q: 'Is ProPostly really free?',
    a: 'Yes. The free plan includes 5 uses per feature per month with no credit card required. You can install and start using it immediately.',
  },
  {
    q: 'Which browsers does it work on?',
    a: 'Chrome, Brave, Opera, and Vivaldi. Any Chromium-based browser supports the extension.',
  },
  {
    q: 'Does it work on both LinkedIn and Reddit?',
    a: 'Yes. LinkedIn features and Reddit features are completely separate. You can use the free tier for both, or upgrade one or both independently.',
  },
  {
    q: 'Is my data safe?',
    a: 'ProPostly only reads the LinkedIn or Reddit page you are actively viewing. No data is stored on our servers or sold to third parties.',
  },
  {
    q: 'What is Deep Lead Search?',
    a: 'Deep Lead Search scans LinkedIn people search results and rates each profile as Hot or Warm based on your target description, then writes a personalized DM for each lead.',
  },
  {
    q: 'What is the anti-ban protection?',
    a: 'Every Reddit post generated by ProPostly goes through an automatic check to flag content that could trigger Reddit spam filters, so you can post with confidence.',
  },
  {
    q: 'Can I cancel anytime?',
    a: 'Yes. You can cancel your subscription from inside the extension at any time. No contracts, no cancellation fees.',
  },
]

function FAQItem({ faq, index }) {
  const [open, setOpen] = useState(false)

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.35, delay: index * 0.06 }}
      style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}
      className="last:border-0"
    >
      <button
        onClick={() => setOpen(!open)}
        className="flex items-start justify-between w-full py-5 text-left gap-4"
      >
        <span className="text-sm font-semibold text-white">{faq.q}</span>
        <motion.span
          animate={{ rotate: open ? 45 : 0 }}
          transition={{ duration: 0.2 }}
          className="flex-shrink-0 mt-0.5 text-slate-500"
        >
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
        </motion.span>
      </button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden"
          >
            <p className="pb-5 text-sm text-slate-400 leading-relaxed">{faq.a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

export default function FAQ() {
  return (
    <section id="faq" className="py-20 px-4 sm:px-6 lg:px-8" style={{ background: '#080c18' }}>
      <div className="max-w-3xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Frequently asked questions
          </h2>
          <p className="text-slate-400 text-lg">Everything you need to know before installing.</p>
        </motion.div>

        <div className="rounded-2xl px-6" style={{ background: '#111827', border: '1px solid rgba(255,255,255,0.07)' }}>
          {faqs.map((faq, i) => (
            <FAQItem key={faq.q} faq={faq} index={i} />
          ))}
        </div>
      </div>
    </section>
  )
}
